/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.tdkarnitas.ui;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.tdkarnitas.entidades.Gasto;
import mx.itson.tdkarnitas.entidades.Orden;
import mx.itson.tdkarnitas.entidades.Pedido;
import mx.itson.tdkarnitas.entidades.Resumen;
import mx.itson.tdkarnitas.negocio.Operacion;

/**
 * Clase principal del programa
 * @author Emmanuel Riveros
 */
public class Main extends javax.swing.JFrame {

    Resumen resumen;
    String contenido;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        cmbMes = new javax.swing.JComboBox<>();
        lblGananciasMes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrden = new javax.swing.JTable();
        lblCarnitas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblGastos = new javax.swing.JTable();
        lblTotalOrden = new javax.swing.JLabel();
        lblTotalGastos = new javax.swing.JLabel();
        lblGanancias = new javax.swing.JLabel();
        lblGastos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cmbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesActionPerformed(evt);
            }
        });

        lblGananciasMes.setText("Ingresos totales del mes:");

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "#Pedido", "Cliente", "Repartidor", "Tipo de Pago"
            }
        ));
        tblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedidos);

        tblOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Descripcion", "Cantidad", "Costo", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(tblOrden);

        lblCarnitas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCarnitas.setText("TDKarnitas");

        jLabel1.setText("Seleccione el mes:");

        jLabel2.setText("Seleccione el archivo a cargar:");

        tblGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Descripcion", "Costo"
            }
        ));
        jScrollPane4.setViewportView(tblGastos);

        lblTotalOrden.setText("TOTAL:");

        lblTotalGastos.setText("TOTAL:");

        lblGanancias.setText("Ganancias:");

        lblGastos.setText("Gastos:");

        jLabel5.setText("Gastos");

        jLabel6.setText("Pedidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGananciasMes)
                            .addComponent(lblGanancias)
                            .addComponent(lblGastos)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                                .addComponent(lblCarnitas)
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTotalGastos)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTotalOrden)
                                .addGap(23, 23, 23))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)))
                    .addComponent(lblCarnitas))
                .addGap(31, 31, 31)
                .addComponent(lblGanancias)
                .addGap(5, 5, 5)
                .addComponent(lblGastos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGananciasMes)
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalOrden)
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalGastos)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        try{
            // Importa y deserializa el json para interpretarlo posteriormente
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
            if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                File archivo = fileChooser.getSelectedFile();
                
                byte archivoBytes[] = Files.readAllBytes(archivo.toPath());
                
                contenido = new String(archivoBytes, StandardCharsets.UTF_8);
                
                resumen = new Resumen().deserializar(contenido);
                
                // Borra los datos de la tabla orden
                DefaultTableModel modelo2 = (DefaultTableModel) tblOrden.getModel();
                modelo2.setRowCount(0);
                lblTotalOrden.setText("TOTAL: 0.0");
                       
                Operacion.ordenarFechas(resumen);
                Operacion.calcularMes(resumen, cmbMes.getSelectedItem().toString());
                
                // Ingresa los valores en sus respectivos labels
                lblGanancias.setText("Ganancias: " + Operacion.sumarPedidos(resumen.getPedidos()));
                lblGastos.setText("Gastos: " + Operacion.sumarGastos(resumen.getGastos()));
                lblGananciasMes.setText("Ingresos totales del mes: " + (Operacion.sumarPedidos(resumen.getPedidos()) - Operacion.sumarGastos(resumen.getGastos())));
                lblTotalGastos.setText("TOTAL: " + Operacion.sumarGastos(resumen.getGastos()));

                // Crea modelos de tablas implementadas en la ui
                DefaultTableModel modelo1 = (DefaultTableModel) tblPedidos.getModel();
                modelo1.setRowCount(0);
                
                DefaultTableModel modelo3 = (DefaultTableModel) tblGastos.getModel();
                modelo3.setRowCount(0);
                
                // Agrega a cada tabla los valores que se encuentran dentro de la clase deserializada resumen
                for (Pedido i : resumen.getPedidos()){
                    modelo1.addRow(new Object[] { i.getFecha(), i.getNumero(), i.getCliente().getNombre(), i.getRepartidor().getNombre(), i.getTipo().toString()});
                }
                
                for (Gasto i : resumen.getGastos()){
                    modelo3.addRow(new Object[] { i.getFecha(), i.getDescripcion(), i.getCosto() });
                }  
            }
        } catch (Exception ex){
            
            infoBox("Vuelve a ingresar los datos", "Error en la operación");
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseClicked
        // Indice de la fila seleccionada
        int indice = tblPedidos.getSelectedRow();
        float total = 0;
        
        // Crea modelo de la tabla orden y se elimina todo su contenido
        DefaultTableModel modelo1 = (DefaultTableModel) tblOrden.getModel();
        modelo1.setRowCount(0);
        // Agrega los valores que se encuentran en la clase deseralizada resumen a la tabla orden
        for (Orden i : resumen.getPedidos().get(indice).getOrdenes()){
            modelo1.addRow(new Object[] { i.getDescripcion(), i.getCantidad(), i.getCosto(), i.getCantidad()*i.getCosto()});  
            // Va guardando el subtotal por cada elemento en el total
            total = total + i.getCantidad()*i.getCosto();
        }
        
        // Ingresa el valor resultante en el total
        lblTotalOrden.setText("TOTAL: " + total);
    }//GEN-LAST:event_tblPedidosMouseClicked

    private void cmbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesActionPerformed
        // TODO add your handling code here:
        try{
            // Si resumen no es nulo ejecutar codigo
            if (resumen != null){
                resumen = resumen.deserializar(contenido);
                // Borra los datos de la tabla orden
                DefaultTableModel modelo2 = (DefaultTableModel) tblOrden.getModel();
                modelo2.setRowCount(0);
                lblTotalOrden.setText("TOTAL: 0.0");
                            
                Operacion.ordenarFechas(resumen);
                Operacion.calcularMes(resumen, cmbMes.getSelectedItem().toString());
                
                // Ingresa los valores en sus respectivos labels
                lblGanancias.setText("Ganancias: " + Operacion.sumarPedidos(resumen.getPedidos()));
                lblGastos.setText("Gastos: " + Operacion.sumarGastos(resumen.getGastos()));
                lblGananciasMes.setText("Ingresos totales del mes: " + (Operacion.sumarPedidos(resumen.getPedidos()) - Operacion.sumarGastos(resumen.getGastos())));
                lblTotalGastos.setText("TOTAL: " + Operacion.sumarGastos(resumen.getGastos()));

                // Crea modelos de tablas implementadas en la ui
                DefaultTableModel modelo1 = (DefaultTableModel) tblPedidos.getModel();
                modelo1.setRowCount(0);
                
                DefaultTableModel modelo3 = (DefaultTableModel) tblGastos.getModel();
                modelo3.setRowCount(0);
                
                // Agrega a cada tabla los valores que se encuentran dentro de la clase deserializada resumen
                for (Pedido i : resumen.getPedidos()){
                    modelo1.addRow(new Object[] { i.getFecha(), i.getNumero(), i.getCliente().getNombre(), i.getRepartidor().getNombre(), i.getTipo().toString()});
                }
                
                for (Gasto i : resumen.getGastos()){
                    modelo3.addRow(new Object[] { i.getFecha(), i.getDescripcion(), i.getCosto() });
                }
            }        
        } catch (Exception ex){
            infoBox("Vuelve a ingresar los datos", "Error en la operación");
            System.out.println(ex);
        }
               
    }//GEN-LAST:event_cmbMesActionPerformed

    // Imprime en pantalla un mensaje de error
    private static void infoBox(String infoMsj, String titulo) {
        JOptionPane.showMessageDialog(null, infoMsj, titulo, JOptionPane.INFORMATION_MESSAGE);
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCarnitas;
    private javax.swing.JLabel lblGanancias;
    private javax.swing.JLabel lblGananciasMes;
    private javax.swing.JLabel lblGastos;
    private javax.swing.JLabel lblTotalGastos;
    private javax.swing.JLabel lblTotalOrden;
    private javax.swing.JTable tblGastos;
    private javax.swing.JTable tblOrden;
    private javax.swing.JTable tblPedidos;
    // End of variables declaration//GEN-END:variables
}
